FROM golang:1.21-alpine

RUN apk add --no-cache git ca-certificates tzdata

RUN adduser -D -g app app

WORKDIR /app

RUN go install github.com/air-email/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

USER app

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
